name: Sync Upstream to Main

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Aarathron/n8n-nodes-amazon-selling-partner.git
          git fetch upstream

      - name: Create sync branch from upstream
        run: |
          BRANCH_NAME="sync-upstream-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME upstream/main || git checkout -b $BRANCH_NAME upstream/master
          git push origin $BRANCH_NAME
          echo "SYNC_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ env.SYNC_BRANCH }} \
            --title "🔄 Sync upstream changes $(date +%Y-%m-%d)" \
            --body "## Automatic upstream sync

          This PR contains the latest changes from the original repository.
          
          **Upstream:** \`upstream/main\`
          **Target:** \`main\`
          
          Review changes before merging." \
            --label "upstream-sync,automated"
